### Load kedro

In [1]:
import os

os.chdir("../../")

%load_ext kedro.ipython

[05/05/26 20:07:50] INFO     Using                                                                  ]8;id=763070;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=697387;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\framework\project\__init__.py#269\269]8;;\
                             'c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pac
                             kages\kedro\framework\project\rich_logging.yml' as logging
                             configuration.

                    INFO     Registered line magic '%reload_kedro'                                   ]8;id=165059;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=252319;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#64\64]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=422744;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=303957;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#66\66]8;;\

                    INFO     Resolved project path as:                                              ]8;id=481143;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=221950;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#181\181]8;;\
                             c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\cxr-training-pipeli
                             ne.
                             To set a different path, run '%reload_kedro <project_root>'

[05/05/26 20:07:53] WARNING  c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pack ]8;id=647607;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=817614;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             ages\requests\__init__.py:113: RequestsDependencyWarning: urllib3
                             (2.6.3) or chardet (6.0.0.post1)/charset_normalizer (3.4.4) doesn't
                             match a supported version!
                               warnings.warn(

[05/05/26 20:07:57] WARNING  c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pack ]8;id=10009;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=307626;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             ages\mlflow\pyfunc\utils\data_validation.py:186: UserWarning: [33mAdd
                             type hints to the `predict` method to enable data validation and
                             automatic signature inference during model logging. Check
                             https://mlflow.org/docs/latest/model/python_model.html#type-hint-usage
                             -in-pythonmodel for more details.[0m
                               color_warning(

                    INFO     Registering new custom resolver: 'km.random_name'                    ]8;id=50888;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\framework\hooks\mlflow_hook.py\mlflow_hook.py]8;;\:]8;id=724397;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\framework\hooks\mlflow_hook.py#65\65]8;;\

                    INFO     The 'tracking_uri' key in mlflow.yml is relative            ]8;id=925030;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\config\kedro_mlflow_config.py\kedro_mlflow_config.py]8;;\:]8;id=501569;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\config\kedro_mlflow_config.py#294\294]8;;\
                             ('server.mlflow_(tracking|registry)_uri = mlruns'). It is
                             converted to a valid uri:
                             'file:///C:/Users/barte/OneDrive/Pulpit/dnn-cxr-diagnostics
                             /cxr-training-pipeline/mlruns'

                    WARNING  c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pack ]8;id=738480;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=352385;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             ages\mlflow\tracking\_tracking_service\utils.py:184: FutureWarning:
                             The filesystem tracking backend (e.g., './mlruns') is deprecated as of
                             February 2026. Consider transitioning to a database backend (e.g.,
                             'sqlite:///mlflow.db') to take advantage of the latest MLflow
                             features. See
                             https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store
                             for migration guidance.
                               return FileStore(store_uri, store_uri)

[05/05/26 20:08:22] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=336629;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=143085;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_telemetry\plugin.py#242\242]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

[05/05/26 20:08:23] INFO     Kedro project cxr-training-pipeline                                    ]8;id=190286;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=795081;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#147\147]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=169128;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=964795;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#148\148]8;;\
                             'pipelines'

[05/05/26 20:08:24] INFO     Registered line magic 'run_viz'                                        ]8;id=386233;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=738486;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#154\154]8;;\

### Imports

In [2]:
import torch
from src.cxr_training_pipeline.models.classifier import ChestXRayClassifier
from sklearn.metrics import classification_report, confusion_matrix
from tqdm import tqdm
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Loading results

In [3]:
best_thresholds = pd.read_json(r"data\08_reporting\cxr-classification-efficientb0-224-no-scaling\efficientb0_224_no-scaling\best_thresholds.json", orient="index")
test_metrics_default = pd.read_json(r"data\08_reporting\cxr-classification-efficientb0-224-no-scaling\efficientb0_224_no-scaling\test_metrics_default.json", orient="index")
test_metrics_tuned = pd.read_json(r"data\08_reporting\cxr-classification-efficientb0-224-no-scaling\efficientb0_224_no-scaling\test_metrics_tuned.json", orient="index")
test_metrics_comparison = pd.read_parquet(r"data\08_reporting\cxr-classification-efficientb0-224-no-scaling\efficientb0_224_no-scaling\test_metrics_comparison.parquet")
test_per_class_comparison = pd.read_parquet(r"data\08_reporting\cxr-classification-efficientb0-224-no-scaling\efficientb0_224_no-scaling\test_per_class_comparison.parquet")

In [4]:
best_thresholds

                       0
Infiltration        0.61
Effusion            0.71
Atelectasis         0.67
Nodule              0.57
Mass                0.63
Pneumothorax        0.70
Consolidation       0.70
Pleural_Thickening  0.59
Cardiomegaly        0.75
Emphysema           0.58
Edema               0.77
Fibrosis            0.53
Pneumonia           0.52
Hernia              0.42

In [5]:
test_metrics_default

                        0
f1_macro         0.186130
f1_micro         0.261542
precision_macro  0.118136
precision_micro  0.164281
recall_macro     0.476372
recall_micro     0.641109
auroc_macro      0.679285
ap_macro         0.139934

In [6]:
test_metrics_tuned

                        0
f1_macro         0.184033
f1_micro         0.268334
precision_macro  0.158260
precision_micro  0.213696
recall_macro     0.246683
recall_micro     0.360509
auroc_macro      0.679285
ap_macro         0.139934

In [7]:
test_metrics_comparison

            metric  default_0_5     tuned     delta
0         f1_macro     0.186130  0.184033 -0.002098
1         f1_micro     0.261542  0.268334  0.006791
2  precision_macro     0.118136  0.158260  0.040124
3  precision_micro     0.164281  0.213696  0.049415
4     recall_macro     0.476372  0.246683 -0.229690
5     recall_micro     0.641109  0.360509 -0.280600
6      auroc_macro     0.679285  0.679285  0.000000
7         ap_macro     0.139934  0.139934  0.000000

In [8]:
test_per_class_comparison

,class_name,f1_default_0_5,precision_default_0_5,recall_default_0_5,auroc_default_0_5,ap_default_0_5,f1_tuned,precision_tuned,recall_tuned,auroc_tuned,ap_tuned,threshold_tuned,f1_delta,precision_delta,recall_delta
0,Infiltration,0.415731,0.280109,0.805955,0.633435,0.336634,0.416962,0.329687,0.567081,0.633435,0.336634,0.61,0.001231,0.049578,-0.238874
1,Effusion,0.391590,0.258036,0.811722,0.707505,0.343253,0.383114,0.319518,0.478317,0.707505,0.343253,0.71,-0.008476,0.061482,-0.333405
2,Atelectasis,0.280005,0.174300,0.711497,0.660573,0.225559,0.287907,0.245073,0.348887,0.660573,0.225559,0.67,0.007903,0.070773,-0.362611
3,Nodule,0.138129,0.081257,0.460259,0.584753,0.084650,0.136105,0.093484,0.250154,0.584753,0.084650,0.57,-0.002024,0.012226,-0.210105
4,Mass,0.172178,0.106636,0.446796,0.622238,0.112746,0.180267,0.130771,0.290046,0.622238,0.112746,0.63,0.008089,0.024135,-0.156751
5,Pneumothorax,0.283108,0.191659,0.541463,0.695533,0.219427,0.236141,0.282212,0.203002,0.695533,0.219427,0.70,-0.046966,0.090553,-0.338462
6,Consolidation,0.188981,0.109005,0.709642,0.679319,0.118832,0.181305,0.133333,0.283196,0.679319,0.118832,0.70,-0.007676,0.024329,-0.426446
7,Pleural_Thickening,0.139634,0.083433,0.427822,0.658711,0.083790,0.140690,0.093952,0.279965,0.658711,0.083790,0.59,0.001056,0.010519,-0.147857
8,Cardiomegaly,0.188999,0.116446,0.501403,0.765911,0.170724,0.223112,0.287187,0.182413,0.765911,0.170724,0.75,0.034114,0.170741,-0.318990
9,Emphysema,0.139509,0.087555,0.343092,0.666785,0.081565,0.131889,0.099672,0.194876,0.666785,0.081565,0.58,-0.007620,0.012117,-0.148216
10,Edema,0.154087,0.086680,0.692973,0.780741,0.099983,0.156570,0.123067,0.215135,0.780741,0.099983,0.77,0.002483,0.036387,-0.477838
11,Fibrosis,0.069510,0.045082,0.151724,0.718280,0.038820,0.065385,0.045333,0.117241,0.718280,0.038820,0.53,-0.004126,0.000251,-0.034483
12,Pneumonia,0.044362,0.033708,0.064865,0.603462,0.030057,0.037008,0.032345,0.043243,0.603462,0.030057,0.52,-0.007354,-0.001363,-0.021622
13,Hernia,0.000000,0.000000,0.000000,0.732743,0.013036,0.000000,0.000000,0.000000,0.732743,0.013036,0.42,0.000000,0.000000,0.000000

### Testing model with given thresholds

In [9]:
def load_model(checkpoint_path, model_type, transition_dim, num_classes=14):
    model = ChestXRayClassifier(backbone_name=model_type,
                                pretrained=True,
                                grayscale=True,
                                num_classes=num_classes,
                                transition_dim=transition_dim)
    checkpoint = torch.load(checkpoint_path, map_location=torch.device("cpu"), weights_only=False)

    model_state_dict = checkpoint["state_dict"]

    model_state_dict = {
        k.replace("model.", "", 1): v
        for k, v in model_state_dict.items()
        if not k.startswith("thresholds") and "thresholds" not in k
    }
    model.load_state_dict(model_state_dict)

    return model

In [10]:
best_checkpoint_path = r"data\06_models\cxr-classification-efficientb0-224-no-scaling\checkpoints\best-epoch=27.ckpt"
effnetb0_classifier = load_model(best_checkpoint_path, model_type="efficientnet_b0", transition_dim=1280, num_classes=14)

effnetb0_classifier

ChestXRayClassifier(
  (backbone): TorchvisionBackbone(
    (features): Sequential(
      (0): Conv2dNormActivation(
        (0): Conv2d(1, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): SiLU(inplace=True)
      )
      (1): Sequential(
        (0): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
              (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (1): SqueezeExcitation(
              (avgpool): AdaptiveAvgPool2d(output_size=1)
              (fc1): Conv2d(32, 8, kernel_size=(1, 1), stride=(1, 1))
              (fc2): Conv2d(8, 32, kernel_size=(1, 1), stride=(1, 1))
              (activation): SiLU(inplace=True)
              (scale_activation): Sigmoid()
            )
            (2): Conv2dNormActivation(
              (0): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.0, mode=row)
        )
      )
      (2): Sequential(
        (0): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(16, 96, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (1): Conv2dNormActivation(
              (0): Conv2d(96, 96, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=96, bias=False)
              (1): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (2): SqueezeExcitation(
              (avgpool): AdaptiveAvgPool2d(output_size=1)
              (fc1): Conv2d(96, 4, kernel_size=(1, 1), stride=(1, 1))
              (fc2): Conv2d(4, 96, kernel_size=(1, 1), stride=(1, 1))
              (activation): SiLU(inplace=True)
              (scale_activation): Sigmoid()
            )
            (3): Conv2dNormActivation(
              (0): Conv2d(96, 24, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.0125, mode=row)
        )
        (1): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(24, 144, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (1): Conv2dNormActivation(
              (0): Conv2d(144, 144, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=144, bias=False)
              (1): BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (2): SqueezeExcitation(
              (avgpool): AdaptiveAvgPool2d(output_size=1)
              (fc1): Conv2d(144, 6, kernel_size=(1, 1), stride=(1, 1))
              (fc2): Conv2d(6, 144, kernel_size=(1, 1), stride=(1, 1))
              (activation): SiLU(inplace=True)
              (scale_activation): Sigmoid()
            )
            (3): Conv2dNormActivation(
              (0): Conv2d(144, 24, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.025, mode=row)
        )
      )
      (3): Sequential(
        (0): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(24, 144, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (1): Conv2dNormActivation(
              (0): Conv2d(144, 144, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2), groups=144, bias=False)
              (1): BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (2): SqueezeExcitation(
              (avgpool): AdaptiveAvgPool2d(output_size=1)
              (fc1): Conv2d(144, 6, kernel_size=(1, 1), stride=(1, 1))
              (fc2): Conv2d(6, 144, kernel_size=(1, 1), stride=(1, 1))
              (activation): SiLU(inplace=True)
              (scale_activation): Sigmoid()
            )
            (3): Conv2dNormActivation(
              (0): Conv2d(144, 40, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.037500000000000006, mode=row)
        )
        (1): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(40, 240, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(240, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (1): Conv2dNormActivation(
              (0): Conv2d(240, 240, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=240, bias=False)
              (1): BatchNorm2d(240, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (2): SqueezeExcitation(
              (avgpool): AdaptiveAvgPool2d(output_size=1)
              (fc1): Conv2d(240, 10, kernel_size=(1, 1), stride=(1, 1))
              (fc2): Conv2d(10, 240, kernel_size=(1, 1), stride=(1, 1))
              (activation): SiLU(inplace=True)
              (scale_activation): Sigmoid()
            )
            (3): Conv2dNormActivation(
              (0): Conv2d(240, 40, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.05, mode=row)
        )
      )
      (4): Sequential(
        (0): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(40, 240, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(240, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (1): Conv2dNormActivation(
              (0): Conv2d(240, 240, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=240, bias=False)
              (1): BatchNorm2d(240, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (2): SqueezeExcitation(
              (avgpool): AdaptiveAvgPool2d(output_size=1)
              (fc1): Conv2d(240, 10, kernel_size=(1, 1), stride=(1, 1))
              (fc2): Conv2d(10, 240, kernel_size=(1, 1), stride=(1, 1))
              (activation): SiLU(inplace=True)
              (scale_activation): Sigmoid()
            )
            (3): Conv2dNormActivation(
              (0): Conv2d(240, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.0625, mode=row)
        )
        (1): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (1): Conv2dNormActivation(
              (0): Conv2d(480, 480, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=480, bias=False)
              (1): BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (2): SqueezeExcitation(
              (avgpool): AdaptiveAvgPool2d(output_size=1)
              (fc1): Conv2d(480, 20, kernel_size=(1, 1), stride=(1, 1))
              (fc2): Conv2d(20, 480, kernel_size=(1, 1), stride=(1, 1))
              (activation): SiLU(inplace=True)
              (scale_activation): Sigmoid()
            )
            (3): Conv2dNormActivation(
              (0): Conv2d(480, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.07500000000000001, mode=row)
        )
        (2): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (1): Conv2dNormActivation(
              (0): Conv2d(480, 480, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=480, bias=False)
              (1): BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (2): SqueezeExcitation(
              (avgpool): AdaptiveAvgPool2d(output_size=1)
              (fc1): Conv2d(480, 20, kernel_size=(1, 1), stride=(1, 1))
              (fc2): Conv2d(20, 480, kernel_size=(1, 1), stride=(1, 1))
              (activation): SiLU(inplace=True)
              (scale_activation): Sigmoid()
            )
            (3): Conv2dNormActivation(
              (0): Conv2d(480, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.08750000000000001, mode=row)
        )
      )
      (5): Sequential(
        (0): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (1): Conv2dNormActivation(
              (0): Conv2d(480, 480, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=480, bias=False)
              (1): BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (2): SqueezeExcitation(
              (avgpool): AdaptiveAvgPool2d(output_size=1)
              (fc1): Conv2d(480, 20, kernel_size=(1, 1), stride=(1, 1))
              (fc2): Conv2d(20, 480, kernel_size=(1, 1), stride=(1, 1))
              (activation): SiLU(inplace=True)
              (scale_activation): Sigmoid()
            )
            (3): Conv2dNormActivation(
              (0): Conv2d(480, 112, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(112, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.1, mode=row)
        )
        (1): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (1): Conv2dNormActivation(
              (0): Conv2d(672, 672, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=672, bias=False)
              (1): BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (2): SqueezeExcitation(
              (avgpool): AdaptiveAvgPool2d(output_size=1)
              (fc1): Conv2d(672, 28, kernel_size=(1, 1), stride=(1, 1))
              (fc2): Conv2d(28, 672, kernel_size=(1, 1), stride=(1, 1))
              (activation): SiLU(inplace=True)
              (scale_activation): Sigmoid()
            )
            (3): Conv2dNormActivation(
              (0): Conv2d(672, 112, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(112, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.1125, mode=row)
        )
        (2): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (1): Conv2dNormActivation(
              (0): Conv2d(672, 672, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=672, bias=False)
              (1): BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (2): SqueezeExcitation(
              (avgpool): AdaptiveAvgPool2d(output_size=1)
              (fc1): Conv2d(672, 28, kernel_size=(1, 1), stride=(1, 1))
              (fc2): Conv2d(28, 672, kernel_size=(1, 1), stride=(1, 1))
              (activation): SiLU(inplace=True)
              (scale_activation): Sigmoid()
            )
            (3): Conv2dNormActivation(
              (0): Conv2d(672, 112, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(112, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.125, mode=row)
        )
      )
      (6): Sequential(
        (0): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (1): Conv2dNormActivation(
              (0): Conv2d(672, 672, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2), groups=672, bias=False)
              (1): BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (2): SqueezeExcitation(
              (avgpool): AdaptiveAvgPool2d(output_size=1)
              (fc1): Conv2d(672, 28, kernel_size=(1, 1), stride=(1, 1))
              (fc2): Conv2d(28, 672, kernel_size=(1, 1), stride=(1, 1))
              (activation): SiLU(inplace=True)
              (scale_activation): Sigmoid()
            )
            (3): Conv2dNormActivation(
              (0): Conv2d(672, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.1375, mode=row)
        )
        (1): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (1): Conv2dNormActivation(
              (0): Conv2d(1152, 1152, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=1152, bias=False)
              (1): BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (2): SqueezeExcitation(
              (avgpool): AdaptiveAvgPool2d(output_size=1)
              (fc1): Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1))
              (fc2): Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1))
              (activation): SiLU(inplace=True)
              (scale_activation): Sigmoid()
            )
            (3): Conv2dNormActivation(
              (0): Conv2d(1152, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.15000000000000002, mode=row)
        )
        (2): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (1): Conv2dNormActivation(
              (0): Conv2d(1152, 1152, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=1152, bias=False)
              (1): BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (2): SqueezeExcitation(
              (avgpool): AdaptiveAvgPool2d(output_size=1)
              (fc1): Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1))
              (fc2): Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1))
              (activation): SiLU(inplace=True)
              (scale_activation): Sigmoid()
            )
            (3): Conv2dNormActivation(
              (0): Conv2d(1152, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.1625, mode=row)
        )
        (3): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (1): Conv2dNormActivation(
              (0): Conv2d(1152, 1152, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=1152, bias=False)
              (1): BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): SiLU(inplace=True)
            )
            (2): SqueezeExcitation(
              (avgpool): AdaptiveAvgPool2d(output_size=1)
              (fc1): Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1))
              (fc2): Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1))
              (activation): SiLU(inplace=True)
              (scale_activation): Sigmoid()
            )
            (3): Conv2dNormActivation(
              (0): Conv2d(1152, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
              (1): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            )
          )
          (stochastic_depth): StochasticDepth(p=0.17500000000000002, mode=row)
        )
      )
      (7): Sequential(
        (0): MBConv(
          (block): Sequential(
            (0): Conv2dNormActivation(
              (0): Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False)

In [11]:
def predict_and_analyze(model, dataloader, class_names, threshold=None):
    model.eval()
    device = next(model.parameters()).device
    all_preds = []
    all_targets = []

    with torch.no_grad():
        for batch in tqdm(dataloader, desc="Evaluating"):
            images = batch["image"].to(device)
            targets = batch["target"].cpu()

            outputs = model(images)

            if isinstance(outputs, dict):
                logits = outputs.get("logits")
                if logits is None:
                    raise ValueError("Model returned dict without 'logits'")
            else:
                logits = outputs

            probs = torch.sigmoid(logits).cpu()

            if threshold is None:
                thresh = 0.5
            elif isinstance(threshold, (list, np.ndarray)):
                thresh = torch.tensor(threshold, dtype=probs.dtype)
            else:
                thresh = float(threshold)

            if isinstance(thresh, torch.Tensor):
                thresh = thresh.to(probs.device)
                preds = (probs > thresh).int()
            else:
                preds = (probs > thresh).int()

            all_preds.append(preds)
            all_targets.append(targets.int())

    y_pred = torch.cat(all_preds, axis=0).numpy()
    y_true = torch.cat(all_targets, axis=0).numpy()

    print("Classification Report:")
    print(classification_report(y_true, y_pred, target_names=class_names, zero_division=0))

    for i, name in enumerate(class_names):
        cm = confusion_matrix(y_true[:, i], y_pred[:, i])
        print(f"\nConfusion matrix for {name}:\n{cm}")

In [12]:
import pandas as pd
from src.cxr_training_pipeline.pipelines.data_science.nodes import (
    make_train_val_indices,
    build_transforms_node,
    prepare_datamodule_config,
    build_datamodule_node,
)

train_val_df = pd.read_csv(r"data/02_intermediate/dataset_splits/train_val.csv")
test_df = pd.read_csv(r"data/02_intermediate/dataset_splits/test.csv")

split_params = {"random_state": 42, "val_size": 0.25}
train_idx, val_idx = make_train_val_indices(train_val_df, split_params)


transform_params = {"random_rotation": 10, "random_translate": (0.02, 0.02), "random_scale": (0.9, 1.1)}
train_tfms, eval_tfms = build_transforms_node(transform_params)

parameters = {
    "kwargs": {
        "train_val_images_path": r"data/02_intermediate/precomputed/224/train_images.npy",
        "test_images_path": r"data/02_intermediate/precomputed/224/test_images.npy",
        "y_train_val_path": r"data/02_intermediate/precomputed/224/train_labels.npy",
        "y_test_path": r"data/02_intermediate/precomputed/224/test_labels.npy",
        "batch_size": 32,
        "num_workers": 0,
    }
}

datamodule_config = prepare_datamodule_config(
    train_val_df=train_val_df,
    test_df=test_df,
    train_idx=train_idx,
    val_idx=val_idx,
    train_tfms=train_tfms,
    eval_tfms=eval_tfms,
    parameters=parameters,
)

datamodule = build_datamodule_node("image_only", datamodule_config)


datamodule.setup(stage="fit")
train_loader = datamodule.train_dataloader()
val_loader = datamodule.val_dataloader()

datamodule.setup(stage="test")
test_loader = datamodule.test_dataloader()

batch = next(iter(val_loader))
print("val batch image shape:", batch["image"].shape, "targets shape:", batch["target"].shape)
print("n_train:", len(train_loader.dataset), "n_val:", len(val_loader.dataset), "n_test:", len(test_loader.dataset))

val batch image shape: torch.Size([32, 1, 224, 224]) targets shape: torch.Size([32, 14])
n_train: 64893 n_val: 21631 n_test: 25596

### Testing predictions vs precomputed predictions

#### Best model - default threshold on test

In [13]:
class_names = test_per_class_comparison["class_name"].tolist()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

effnetb0_classifier.to(device)

predict_and_analyze(effnetb0_classifier, test_loader, class_names)

Evaluating:   0%|          | 1/800 [00:01<14:29,  1.09s/it]

Evaluating: 100%|██████████| 800/800 [01:26<00:00,  9.26it/s]

Classification Report:
                    precision    recall  f1-score   support

      Infiltration       0.29      0.54      0.38      6112
          Effusion       0.33      0.23      0.27      4658
       Atelectasis       0.27      0.16      0.20      3279
            Nodule       0.04      0.06      0.05      1623
              Mass       0.13      0.23      0.17      1748
      Pneumothorax       0.14      0.09      0.11      2665
     Consolidation       0.11      0.10      0.11      1815
Pleural_Thickening       0.09      0.21      0.12      1143
      Cardiomegaly       0.11      0.49      0.19      1069
         Emphysema       0.08      0.04      0.05      1093
             Edema       0.06      0.09      0.08       925
          Fibrosis       0.05      0.09      0.06       435
         Pneumonia       0.00      0.00      0.00       555
            Hernia       0.00      0.00      0.00        86

         micro avg       0.19      0.25      0.22     27206
         macro avg       0.12      0.17      0.13     27206
      weighted avg       0.20      0.25      0.20     27206
       samples avg       0.13      0.15      0.12     27206


Confusion matrix for Infiltration:
[[11382  8102]
 [ 2811  3301]]

Confusion matrix for Effusion:
[[18707  2231]
 [ 3568  1090]]

Confusion matrix for Atelectasis:
[[20910  1407]
 [ 2769   510]]

Confusion matrix for Nodule:
[[21662  2311]
 [ 1520   103]]

Confusion matrix for Mass:
[[21246  2602]
 [ 1352   396]]

Confusion matrix for Pneumothorax:
[[21528  1403]
 [ 2437   228]]

Confusion matrix for Consolidation:
[[22330  1451]
 [ 1630   185]]

Confusion matrix for Pleural_Thickening:
[[22032  2421]
 [  907   236]]

Confusion matrix for Cardiomegaly:
[[20458  4069]
 [  541   528]]

Confusion matrix for Emphysema:
[[24029   474]
 [ 1051    42]]

Confusion matrix for Edema:
[[23414  1257]
 [  839    86]]

Confusion matrix for Fibrosis:
[[24333   828]
 [  395    40]]

Confusion matrix for Pneumonia:
[[25035     6]
 [  555     0]]

Confusion matrix for Hernia:
[[25510     0]
 [   86     0]]

#### Best model - "best thresholds" on test

In [14]:
thresholds = best_thresholds[0].tolist()

In [15]:
predict_and_analyze(effnetb0_classifier, test_loader, class_names, threshold=thresholds)

Evaluating: 100%|██████████| 800/800 [01:09<00:00, 11.57it/s]

Classification Report:
                    precision    recall  f1-score   support

      Infiltration       0.33      0.18      0.24      6112
          Effusion       0.35      0.05      0.09      4658
       Atelectasis       0.26      0.02      0.03      3279
            Nodule       0.03      0.00      0.00      1623
              Mass       0.14      0.09      0.11      1748
      Pneumothorax       0.20      0.00      0.01      2665
     Consolidation       0.07      0.01      0.01      1815
Pleural_Thickening       0.10      0.09      0.10      1143
      Cardiomegaly       0.25      0.13      0.17      1069
         Emphysema       0.06      0.01      0.02      1093
             Edema       0.05      0.01      0.01       925
          Fibrosis       0.05      0.06      0.05       435
         Pneumonia       0.00      0.00      0.00       555
            Hernia       0.00      0.00      0.00        86

         micro avg       0.23      0.07      0.11     27206
         macro avg       0.13      0.05      0.06     27206
      weighted avg       0.22      0.07      0.09     27206
       samples avg       0.06      0.04      0.05     27206


Confusion matrix for Infiltration:
[[17249  2235]
 [ 4989  1123]]

Confusion matrix for Effusion:
[[20497   441]
 [ 4425   233]]

Confusion matrix for Atelectasis:
[[22167   150]
 [ 3226    53]]

Confusion matrix for Nodule:
[[23940    33]
 [ 1622     1]]

Confusion matrix for Mass:
[[22845  1003]
 [ 1585   163]]

Confusion matrix for Pneumothorax:
[[22903    28]
 [ 2658     7]]

Confusion matrix for Consolidation:
[[23597   184]
 [ 1802    13]]

Confusion matrix for Pleural_Thickening:
[[23506   947]
 [ 1037   106]]

Confusion matrix for Cardiomegaly:
[[24122   405]
 [  935   134]]

Confusion matrix for Emphysema:
[[24317   186]
 [ 1082    11]]

Confusion matrix for Edema:
[[24539   132]
 [  918     7]]

Confusion matrix for Fibrosis:
[[24673   488]
 [  410    25]]

Confusion matrix for Pneumonia:
[[25039     2]
 [  555     0]]

Confusion matrix for Hernia:
[[25510     0]
 [   86     0]]

#### Best model - default threshold on val

In [16]:
predict_and_analyze(effnetb0_classifier, val_loader, class_names, threshold=0.5)

Evaluating:   0%|          | 3/676 [00:00<01:38,  6.84it/s]

Evaluating: 100%|██████████| 676/676 [01:28<00:00,  7.67it/s]

Classification Report:
                    precision    recall  f1-score   support

      Infiltration       0.25      0.33      0.29      3448
          Effusion       0.33      0.23      0.27      2136
       Atelectasis       0.26      0.15      0.19      2083
            Nodule       0.06      0.04      0.05      1174
              Mass       0.11      0.22      0.15      1017
      Pneumothorax       0.06      0.05      0.05       680
     Consolidation       0.11      0.10      0.10       723
Pleural_Thickening       0.07      0.21      0.11       556
      Cardiomegaly       0.07      0.45      0.12       411
         Emphysema       0.02      0.01      0.02       342
             Edema       0.05      0.10      0.07       343
          Fibrosis       0.06      0.12      0.08       315
         Pneumonia       0.00      0.00      0.00       233
            Hernia       0.00      0.00      0.00        26

         micro avg       0.16      0.20      0.18     13487
         macro avg       0.10      0.14      0.11     13487
      weighted avg       0.19      0.20      0.18     13487
       samples avg       0.06      0.08      0.06     13487


Confusion matrix for Infiltration:
[[14784  3399]
 [ 2310  1138]]

Confusion matrix for Effusion:
[[18493  1002]
 [ 1636   500]]

Confusion matrix for Atelectasis:
[[18658   890]
 [ 1776   307]]

Confusion matrix for Nodule:
[[19567   890]
 [ 1122    52]]

Confusion matrix for Mass:
[[18841  1773]
 [  797   220]]

Confusion matrix for Pneumothorax:
[[20409   542]
 [  648    32]]

Confusion matrix for Consolidation:
[[20307   601]
 [  651    72]]

Confusion matrix for Pleural_Thickening:
[[19547  1528]
 [  440   116]]

Confusion matrix for Cardiomegaly:
[[18717  2503]
 [  227   184]]

Confusion matrix for Emphysema:
[[21125   164]
 [  338     4]]

Confusion matrix for Edema:
[[20712   576]
 [  310    33]]

Confusion matrix for Fibrosis:
[[20694   622]
 [  277    38]]

Confusion matrix for Pneumonia:
[[21394     4]
 [  233     0]]

Confusion matrix for Hernia:
[[21605     0]
 [   26     0]]

#### Best model - "best" threshold on val

In [17]:
predict_and_analyze(effnetb0_classifier, val_loader, class_names, threshold=thresholds)

Evaluating: 100%|██████████| 676/676 [01:26<00:00,  7.77it/s]

Classification Report:
                    precision    recall  f1-score   support

      Infiltration       0.27      0.10      0.15      3448
          Effusion       0.38      0.06      0.11      2136
       Atelectasis       0.25      0.02      0.03      2083
            Nodule       0.00      0.00      0.00      1174
              Mass       0.18      0.09      0.12      1017
      Pneumothorax       0.00      0.00      0.00       680
     Consolidation       0.10      0.01      0.02       723
Pleural_Thickening       0.08      0.07      0.07       556
      Cardiomegaly       0.12      0.06      0.08       411
         Emphysema       0.00      0.00      0.00       342
             Edema       0.01      0.00      0.00       343
          Fibrosis       0.07      0.08      0.07       315
         Pneumonia       0.00      0.00      0.00       233
            Hernia       0.00      0.00      0.00        26

         micro avg       0.20      0.05      0.08     13487
         macro avg       0.10      0.03      0.05     13487
      weighted avg       0.20      0.05      0.08     13487
       samples avg       0.02      0.02      0.02     13487


Confusion matrix for Infiltration:
[[17230   953]
 [ 3098   350]]

Confusion matrix for Effusion:
[[19278   217]
 [ 2004   132]]

Confusion matrix for Atelectasis:
[[19449    99]
 [ 2050    33]]

Confusion matrix for Nodule:
[[20453     4]
 [ 1174     0]]

Confusion matrix for Mass:
[[20192   422]
 [  924    93]]

Confusion matrix for Pneumothorax:
[[20942     9]
 [  680     0]]

Confusion matrix for Consolidation:
[[20829    79]
 [  714     9]]

Confusion matrix for Pleural_Thickening:
[[20644   431]
 [  518    38]]

Confusion matrix for Cardiomegaly:
[[21042   178]
 [  387    24]]

Confusion matrix for Emphysema:
[[21231    58]
 [  342     0]]

Confusion matrix for Edema:
[[21215    73]
 [  342     1]]

Confusion matrix for Fibrosis:
[[20974   342]
 [  291    24]]

Confusion matrix for Pneumonia:
[[21397     1]
 [  233     0]]

Confusion matrix for Hernia:
[[21605     0]
 [   26     0]]

### Testing on the last model

In [18]:
last_effnetb0_classifier = load_model(r"data\06_models\cxr-classification-efficientb0-224-no-scaling\checkpoints\last.ckpt", model_type="efficientnet_b0", transition_dim=1280, num_classes=14).to(device)

#### Last model - default theshold on test

In [19]:
predict_and_analyze(last_effnetb0_classifier, test_loader, class_names)

Evaluating: 100%|██████████| 800/800 [02:01<00:00,  6.56it/s]

Classification Report:
                    precision    recall  f1-score   support

      Infiltration       0.24      1.00      0.39      6112
          Effusion       0.18      1.00      0.31      4658
       Atelectasis       0.13      1.00      0.23      3279
            Nodule       0.00      0.00      0.00      1623
              Mass       0.00      0.00      0.00      1748
      Pneumothorax       0.00      0.00      0.00      2665
     Consolidation       0.07      1.00      0.13      1815
Pleural_Thickening       0.00      0.00      0.00      1143
      Cardiomegaly       0.00      0.00      0.00      1069
         Emphysema       0.00      0.00      0.00      1093
             Edema       0.04      1.00      0.07       925
          Fibrosis       0.00      0.00      0.00       435
         Pneumonia       0.00      0.00      0.00       555
            Hernia       0.00      0.00      0.00        86

         micro avg       0.13      0.62      0.22     27206
         macro avg       0.05      0.36      0.08     27206
      weighted avg       0.11      0.62      0.18     27206
       samples avg       0.13      0.38      0.19     27206


Confusion matrix for Infiltration:
[[    1 19483]
 [    0  6112]]

Confusion matrix for Effusion:
[[    0 20938]
 [    0  4658]]

Confusion matrix for Atelectasis:
[[    0 22317]
 [    0  3279]]

Confusion matrix for Nodule:
[[23973     0]
 [ 1623     0]]

Confusion matrix for Mass:
[[23848     0]
 [ 1748     0]]

Confusion matrix for Pneumothorax:
[[22931     0]
 [ 2665     0]]

Confusion matrix for Consolidation:
[[    0 23781]
 [    0  1815]]

Confusion matrix for Pleural_Thickening:
[[24453     0]
 [ 1143     0]]

Confusion matrix for Cardiomegaly:
[[24527     0]
 [ 1069     0]]

Confusion matrix for Emphysema:
[[24503     0]
 [ 1093     0]]

Confusion matrix for Edema:
[[   28 24643]
 [    0   925]]

Confusion matrix for Fibrosis:
[[25161     0]
 [  435     0]]

Confusion matrix for Pneumonia:
[[25041     0]
 [  555     0]]

Confusion matrix for Hernia:
[[25510     0]
 [   86     0]]

#### Last model - "best" theshold on test

In [20]:
predict_and_analyze(last_effnetb0_classifier, test_loader, class_names, threshold=thresholds)

Evaluating: 100%|██████████| 800/800 [01:17<00:00, 10.35it/s]

Classification Report:
                    precision    recall  f1-score   support

      Infiltration       0.33      0.00      0.00      6112
          Effusion       0.31      0.16      0.21      4658
       Atelectasis       0.16      0.56      0.25      3279
            Nodule       0.00      0.00      0.00      1623
              Mass       0.00      0.00      0.00      1748
      Pneumothorax       0.00      0.00      0.00      2665
     Consolidation       0.00      0.00      0.00      1815
Pleural_Thickening       0.00      0.00      0.00      1143
      Cardiomegaly       0.00      0.00      0.00      1069
         Emphysema       0.00      0.00      0.00      1093
             Edema       0.00      0.00      0.00       925
          Fibrosis       0.00      0.00      0.00       435
         Pneumonia       0.00      0.00      0.00       555
            Hernia       0.00      0.00      0.00        86

         micro avg       0.18      0.09      0.13     27206
         macro avg       0.06      0.05      0.03     27206
      weighted avg       0.15      0.09      0.07     27206
       samples avg       0.08      0.06      0.06     27206


Confusion matrix for Infiltration:
[[19480     4]
 [ 6110     2]]

Confusion matrix for Effusion:
[[19299  1639]
 [ 3916   742]]

Confusion matrix for Atelectasis:
[[12428  9889]
 [ 1440  1839]]

Confusion matrix for Nodule:
[[23973     0]
 [ 1623     0]]

Confusion matrix for Mass:
[[23848     0]
 [ 1748     0]]

Confusion matrix for Pneumothorax:
[[22931     0]
 [ 2665     0]]

Confusion matrix for Consolidation:
[[23781     0]
 [ 1815     0]]

Confusion matrix for Pleural_Thickening:
[[24453     0]
 [ 1143     0]]

Confusion matrix for Cardiomegaly:
[[24527     0]
 [ 1069     0]]

Confusion matrix for Emphysema:
[[24503     0]
 [ 1093     0]]

Confusion matrix for Edema:
[[24671     0]
 [  925     0]]

Confusion matrix for Fibrosis:
[[25161     0]
 [  435     0]]

Confusion matrix for Pneumonia:
[[25041     0]
 [  555     0]]

Confusion matrix for Hernia:
[[25510     0]
 [   86     0]]

#### Last model - default theshold on val

In [21]:
predict_and_analyze(last_effnetb0_classifier, val_loader, class_names)

Evaluating: 100%|██████████| 676/676 [01:51<00:00,  6.04it/s]

Classification Report:
                    precision    recall  f1-score   support

      Infiltration       0.16      1.00      0.27      3448
          Effusion       0.10      1.00      0.18      2136
       Atelectasis       0.10      1.00      0.18      2083
            Nodule       0.00      0.00      0.00      1174
              Mass       0.00      0.00      0.00      1017
      Pneumothorax       0.00      0.00      0.00       680
     Consolidation       0.03      1.00      0.06       723
Pleural_Thickening       0.00      0.00      0.00       556
      Cardiomegaly       0.00      0.00      0.00       411
         Emphysema       0.00      0.00      0.00       342
             Edema       0.02      1.00      0.03       343
          Fibrosis       0.00      0.00      0.00       315
         Pneumonia       0.00      0.00      0.00       233
            Hernia       0.00      0.00      0.00        26

         micro avg       0.08      0.65      0.14     13487
         macro avg       0.03      0.36      0.05     13487
      weighted avg       0.07      0.65      0.13     13487
       samples avg       0.08      0.27      0.12     13487


Confusion matrix for Infiltration:
[[    0 18183]
 [    0  3448]]

Confusion matrix for Effusion:
[[    0 19495]
 [    0  2136]]

Confusion matrix for Atelectasis:
[[    0 19548]
 [    0  2083]]

Confusion matrix for Nodule:
[[20457     0]
 [ 1174     0]]

Confusion matrix for Mass:
[[20614     0]
 [ 1017     0]]

Confusion matrix for Pneumothorax:
[[20951     0]
 [  680     0]]

Confusion matrix for Consolidation:
[[    0 20908]
 [    0   723]]

Confusion matrix for Pleural_Thickening:
[[21075     0]
 [  556     0]]

Confusion matrix for Cardiomegaly:
[[21220     0]
 [  411     0]]

Confusion matrix for Emphysema:
[[21289     0]
 [  342     0]]

Confusion matrix for Edema:
[[   41 21247]
 [    0   343]]

Confusion matrix for Fibrosis:
[[21316     0]
 [  315     0]]

Confusion matrix for Pneumonia:
[[21398     0]
 [  233     0]]

Confusion matrix for Hernia:
[[21605     0]
 [   26     0]]

#### Last model - "best" theshold on val

In [22]:
predict_and_analyze(last_effnetb0_classifier, val_loader, class_names, threshold=thresholds)

Evaluating: 100%|██████████| 676/676 [01:03<00:00, 10.71it/s]

Classification Report:
                    precision    recall  f1-score   support

      Infiltration       0.17      0.00      0.00      3448
          Effusion       0.28      0.16      0.20      2136
       Atelectasis       0.14      0.58      0.22      2083
            Nodule       0.00      0.00      0.00      1174
              Mass       0.00      0.00      0.00      1017
      Pneumothorax       0.00      0.00      0.00       680
     Consolidation       0.00      0.00      0.00       723
Pleural_Thickening       0.00      0.00      0.00       556
      Cardiomegaly       0.00      0.00      0.00       411
         Emphysema       0.00      0.00      0.00       342
             Edema       0.00      0.00      0.00       343
          Fibrosis       0.00      0.00      0.00       315
         Pneumonia       0.00      0.00      0.00       233
            Hernia       0.00      0.00      0.00        26

         micro avg       0.16      0.12      0.13     13487
         macro avg       0.04      0.05      0.03     13487
      weighted avg       0.11      0.12      0.07     13487
       samples avg       0.06      0.05      0.05     13487


Confusion matrix for Infiltration:
[[18178     5]
 [ 3447     1]]

Confusion matrix for Effusion:
[[18591   904]
 [ 1793   343]]

Confusion matrix for Atelectasis:
[[12037  7511]
 [  867  1216]]

Confusion matrix for Nodule:
[[20457     0]
 [ 1174     0]]

Confusion matrix for Mass:
[[20614     0]
 [ 1017     0]]

Confusion matrix for Pneumothorax:
[[20951     0]
 [  680     0]]

Confusion matrix for Consolidation:
[[20908     0]
 [  723     0]]

Confusion matrix for Pleural_Thickening:
[[21075     0]
 [  556     0]]

Confusion matrix for Cardiomegaly:
[[21220     0]
 [  411     0]]

Confusion matrix for Emphysema:
[[21289     0]
 [  342     0]]

Confusion matrix for Edema:
[[21288     0]
 [  343     0]]

Confusion matrix for Fibrosis:
[[21316     0]
 [  315     0]]

Confusion matrix for Pneumonia:
[[21398     0]
 [  233     0]]

Confusion matrix for Hernia:
[[21605     0]
 [   26     0]]

### Conclusions
- Fine-tuning the thresholds gives a worse score.
- This is probably a bug in the code.
- Fix: change `average="binary"` in the code.

### Corrected results

In [28]:
from src.cxr_training_pipeline.pipelines.threshold_finetuning.nodes import tune_thresholds

In [26]:
test_pred_proba = np.load(r"data\07_models_output\cxr-classification-efficientb0-224-no-scaling\efficientb0_224_no-scaling\test_pred_proba.npy")
test_targets = np.load(r"data\07_models_output\cxr-classification-efficientb0-224-no-scaling\efficientb0_224_no-scaling\test_targets.npy")

val_pred_proba = np.load(r"data\07_models_output\cxr-classification-efficientb0-224-no-scaling\efficientb0_224_no-scaling\val_pred_proba.npy")
val_targets = np.load(r"data\07_models_output\cxr-classification-efficientb0-224-no-scaling\efficientb0_224_no-scaling\val_targets.npy")

In [ ]:
# threshold params from configuration file
threshold_params={"start": 0.01,
  "stop": 1.00,
  "step": 0.01,
  "default_threshold": 0.5}

### val tuning

In [33]:
best_thresholds_val, _ = tune_thresholds(val_targets, val_pred_proba, class_names, threshold_params=threshold_params)

Tuning thresholds per class: 100%|██████████| 14/14 [00:32<00:00,  2.35s/it]

In [ ]:
list(best_thresholds_val.values())

dict_values([0.55, 0.64, 0.61, 0.55, 0.61, 0.5700000000000001, 0.64, 0.5800000000000001, 0.75, 0.48000000000000004, 0.77, 0.47000000000000003, 0.52, 0.42000000000000004])

In [39]:
predict_and_analyze(last_effnetb0_classifier, val_loader, class_names, threshold=best_thresholds_val.values())

Evaluating:   0%|          | 0/676 [00:00<?, ?it/s]

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 predict_and_analyze(last_effnetb0_classifier, val_loader, class_names, threshold=best_th     │
│   2                                                                                              │
│                                                                                                  │
│ in predict_and_analyze:28                                                                        │
│                                                                                                  │
│   25 │   │   │   elif isinstance(threshold, (list, np.ndarray)):                                 │
│   26 │   │   │   │   thresh = torch.tensor(threshold, dtype=probs.dtype)                         │
│   27 │   │   │   else:                                                                           │
│ ❱ 28 │   │   │   │   thresh = float(threshold)                                                   │
│   29 │   │   │                                                                                   │
│   30 │   │   │   if isinstance(thresh, torch.Tensor):                                            │
│   31 │   │   │   │   thresh = thresh.to(probs.device)                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: float() argument must be a string or a real number, not 'dict_values'

### test tuning

In [ ]:
best_thresholds_test, _ = tune_thresholds(test_targets, test_pred_proba, class_names)