### Imports

In [35]:
from pathlib import Path

### Load kedro

In [2]:
import os

os.chdir("../../")

%load_ext kedro.ipython

[03/04/26 21:00:40] INFO     Using                                                                  ]8;id=718685;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=983183;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\framework\project\__init__.py#269\269]8;;\
                             'c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pac
                             kages\kedro\framework\project\rich_logging.yml' as logging
                             configuration.

                    INFO     Registered line magic '%reload_kedro'                                   ]8;id=169242;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=280346;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#64\64]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=672948;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=827878;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#66\66]8;;\

                    INFO     Resolved project path as:                                              ]8;id=148431;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=745610;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#181\181]8;;\
                             c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\cxr-training-pipeli
                             ne.
                             To set a different path, run '%reload_kedro <project_root>'

[03/04/26 21:00:44] WARNING  c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pack ]8;id=191246;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=601497;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             ages\requests\__init__.py:113: RequestsDependencyWarning: urllib3
                             (2.6.3) or chardet (6.0.0.post1)/charset_normalizer (3.4.4) doesn't
                             match a supported version!
                               warnings.warn(

[03/04/26 21:00:49] WARNING  c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pack ]8;id=467489;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=725632;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             ages\mlflow\pyfunc\utils\data_validation.py:186: UserWarning: [33mAdd
                             type hints to the `predict` method to enable data validation and
                             automatic signature inference during model logging. Check
                             https://mlflow.org/docs/latest/model/python_model.html#type-hint-usage
                             -in-pythonmodel for more details.[0m
                               color_warning(

[03/04/26 21:00:50] INFO     Registering new custom resolver: 'km.random_name'                    ]8;id=584409;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\framework\hooks\mlflow_hook.py\mlflow_hook.py]8;;\:]8;id=88168;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\framework\hooks\mlflow_hook.py#65\65]8;;\

                    WARNING  No 'mlflow.yml' config file found in environment. Default            ]8;id=757109;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\framework\hooks\mlflow_hook.py\mlflow_hook.py]8;;\:]8;id=19584;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\framework\hooks\mlflow_hook.py#78\78]8;;\
                             configuration will be used. Use ``kedro mlflow init`` command in CLI
                             to customize the configuration.

                    INFO     The 'tracking_uri' key in mlflow.yml is relative            ]8;id=635642;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\config\kedro_mlflow_config.py\kedro_mlflow_config.py]8;;\:]8;id=700767;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\config\kedro_mlflow_config.py#294\294]8;;\
                             ('server.mlflow_(tracking|registry)_uri = mlruns'). It is
                             converted to a valid uri:
                             'file:///C:/Users/barte/OneDrive/Pulpit/dnn-cxr-diagnostics
                             /cxr-training-pipeline/mlruns'

                    WARNING  c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pack ]8;id=869388;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=24490;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             ages\mlflow\tracking\_tracking_service\utils.py:184: FutureWarning:
                             The filesystem tracking backend (e.g., './mlruns') is deprecated as of
                             February 2026. Consider transitioning to a database backend (e.g.,
                             'sqlite:///mlflow.db') to take advantage of the latest MLflow
                             features. See
                             https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store
                             for migration guidance.
                               return FileStore(store_uri, store_uri)

[03/04/26 21:00:58] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=667661;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=12423;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_telemetry\plugin.py#242\242]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

[03/04/26 21:00:59] INFO     Kedro project cxr-training-pipeline                                    ]8;id=560914;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=729203;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#147\147]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=925670;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=10259;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#148\148]8;;\
                             'pipelines'

[03/04/26 21:01:00] INFO     Registered line magic 'run_viz'                                        ]8;id=299003;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=862225;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#154\154]8;;\

### Load CSV

In [5]:
metadata = catalog.load("cxr8_metadata")

[03/04/26 21:01:20] INFO     Loading data from cxr8_metadata (CSVDataset)...                   ]8;id=506306;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=503362;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

In [6]:
metadata.head()

,image_index,finding_labels,follow-up #,patient_id,patient_age,patient_sex,view_position,original_image_width,original_image_height,original_image_pixel_spacing_x,original_image_pixel_spacing_y
0,00000001_000.png,Cardiomegaly,0,1,57,M,PA,2682,2749,0.143,0.143
1,00000001_001.png,Cardiomegaly|Emphysema,1,1,58,M,PA,2894,2729,0.143,0.143
2,00000001_002.png,Cardiomegaly|Effusion,2,1,58,M,PA,2500,2048,0.168,0.168
3,00000002_000.png,No Finding,0,2,80,M,PA,2500,2048,0.171,0.171
4,00000003_001.png,Hernia,0,3,74,F,PA,2500,2048,0.168,0.168

### Dataframe cleaning

This metadata contains a significant amount of useful information; however, not all of it will be used by our classifier.

1. Columns that will be used:

- image_index – identifier of the image, used to locate the corresponding file in the dataset

- finding_labels – labels describing the pathologies present in a given image

- view_position – indicates whether the image was taken in the PA or AP view, which can influence the appearance of certain structures in chest X-rays

- patient_sex – may provide additional context, as some conditions have different prevalence depending on sex

- patient_age – relevant because the probability of certain pathologies increases with age

2. Columns that will not be used:

- follow_up – may indirectly indicate that a patient has already been examined multiple times, which could introduce bias

- patient_id – could lead to data leakage if the same patient appears in both training and test sets

- original image resolution – images will be resized during preprocessing, so the original resolution does not provide useful information for the model

In [18]:
cleaned_metadata = metadata[["image_index", "finding_labels", "patient_age", "patient_sex", "view_position"]]

In [19]:
cleaned_metadata.head()

,image_index,finding_labels,patient_age,patient_sex,view_position
0,00000001_000.png,Cardiomegaly,57,M,PA
1,00000001_001.png,Cardiomegaly|Emphysema,58,M,PA
2,00000001_002.png,Cardiomegaly|Effusion,58,M,PA
3,00000002_000.png,No Finding,80,M,PA
4,00000003_001.png,Hernia,74,F,PA

### Encoding finding labels

Since we are dealing with a multi-label classification problem, the finding_labels column must be split into separate labels and converted into a vector representation. Each image will be associated with a pathology vector, where every position corresponds to a specific pathology.

A value of 1 in a given position indicates that the pathology is present in the image, while a value of 0 indicates that it is not present.

In [20]:
PATHOLOGY_LIST = [
    "Infiltration",
    "Effusion",
    "Atelectasis",
    "Nodule",
    "Mass",
    "Pneumothorax",
    "Consolidation",
    "Pleural_Thickening",
    "Cardiomegaly",
    "Emphysema",
    "Edema",
    "Fibrosis",
    "Pneumonia",
    "Hernia",
]

In [21]:
def labels_to_vector(label_string):
    labels = label_string.split("|")
    return [1 if pathology in labels else 0 for pathology in PATHOLOGY_LIST]


cleaned_metadata["pathology_vector"] = cleaned_metadata["finding_labels"].apply(labels_to_vector)

cleaned_metadata.head()

[03/04/26 21:27:19] WARNING  C:\Users\barte\AppData\Local\Temp\ipykernel_10680\3099144255.py:5:     ]8;id=187128;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=49600;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             SettingWithCopyWarning:
                             A value is trying to be set on a copy of a slice from a DataFrame.
                             Try using .loc = value instead

                             See the caveats in the documentation:
                             https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#
                             returning-a-view-versus-a-copy
                               cleaned_metadata["pathology_vector"] =
                             cleaned_metadata["finding_labels"].apply(labels_to_vector)

,image_index,finding_labels,patient_age,patient_sex,view_position,pathology_vector
0,00000001_000.png,Cardiomegaly,57,M,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]"
1,00000001_001.png,Cardiomegaly|Emphysema,58,M,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]"
2,00000001_002.png,Cardiomegaly|Effusion,58,M,PA,"[0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]"
3,00000002_000.png,No Finding,80,M,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
4,00000003_001.png,Hernia,74,F,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]"

### OHE

In [22]:
labels = cleaned_metadata["finding_labels"].str.get_dummies(sep="|")

cleaned_metadata = cleaned_metadata.join(labels[PATHOLOGY_LIST])

cleaned_metadata.head()

,image_index,finding_labels,patient_age,patient_sex,view_position,pathology_vector,Infiltration,Effusion,Atelectasis,Nodule,Mass,Pneumothorax,Consolidation,Pleural_Thickening,Cardiomegaly,Emphysema,Edema,Fibrosis,Pneumonia,Hernia
0,00000001_000.png,Cardiomegaly,57,M,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]",0,0,0,0,0,0,0,0,1,0,0,0,0,0
1,00000001_001.png,Cardiomegaly|Emphysema,58,M,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]",0,0,0,0,0,0,0,0,1,1,0,0,0,0
2,00000001_002.png,Cardiomegaly|Effusion,58,M,PA,"[0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]",0,1,0,0,0,0,0,0,1,0,0,0,0,0
3,00000002_000.png,No Finding,80,M,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,00000003_001.png,Hernia,74,F,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]",0,0,0,0,0,0,0,0,0,0,0,0,0,1

### Train-Test-Val split

In [27]:
train_val_list = catalog.load("cxr8_train_val_list")
test_list = catalog.load("cxr8_test_list")

[03/04/26 21:29:11] INFO     Loading data from cxr8_train_val_list (TextDataset)...            ]8;id=882602;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=273639;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cxr8_test_list (TextDataset)...                 ]8;id=195645;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=418025;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

In [28]:
train_val_list = [line.strip() for line in train_val_list.splitlines() if line.strip()]
test_list = [line.strip() for line in test_list.splitlines() if line.strip()]

print(f"Number of training/validation samples: {len(train_val_list)}")
print(f"Number of test samples: {len(test_list)}")

Number of training/validation samples: 86524
Number of test samples: 25596

In [29]:
train_val_df = cleaned_metadata[cleaned_metadata["image_index"].isin(train_val_list)]
test_df = cleaned_metadata[cleaned_metadata["image_index"].isin(test_list)]

In [32]:
train_val_df

,image_index,finding_labels,patient_age,patient_sex,view_position,pathology_vector,Infiltration,Effusion,Atelectasis,Nodule,Mass,Pneumothorax,Consolidation,Pleural_Thickening,Cardiomegaly,Emphysema,Edema,Fibrosis,Pneumonia,Hernia
0,00000001_000.png,Cardiomegaly,57,M,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]",0,0,0,0,0,0,0,0,1,0,0,0,0,0
1,00000001_001.png,Cardiomegaly|Emphysema,58,M,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]",0,0,0,0,0,0,0,0,1,1,0,0,0,0
2,00000001_002.png,Cardiomegaly|Effusion,58,M,PA,"[0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]",0,1,0,0,0,0,0,0,1,0,0,0,0,0
3,00000002_000.png,No Finding,80,M,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,00000004_000.png,Mass|Nodule,82,M,AP,"[0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,0,1,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112100,00030789_000.png,Infiltration,51,F,PA,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1,0,0,0,0,0,0,0,0,0,0,0,0,0
112106,00030793_000.png,Mass|Nodule,57,F,PA,"[0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,0,1,1,0,0,0,0,0,0,0,0,0
112108,00030795_000.png,Pleural_Thickening,52,F,PA,"[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]",0,0,0,0,0,0,0,1,0,0,0,0,0,0
112114,00030801_000.png,No Finding,38,M,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,0,0,0,0,0,0,0,0,0,0,0,0
112115,00030801_001.png,Mass|Pneumonia,38,M,PA,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0]",0,0,0,0,1,0,0,0,0,0,0,0,1,0

In [33]:
test_df

,image_index,finding_labels,patient_age,patient_sex,view_position,pathology_vector,Infiltration,Effusion,Atelectasis,Nodule,Mass,Pneumothorax,Consolidation,Pleural_Thickening,Cardiomegaly,Emphysema,Edema,Fibrosis,Pneumonia,Hernia
4,00000003_001.png,Hernia,74,F,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]",0,0,0,0,0,0,0,0,0,0,0,0,0,1
5,00000003_002.png,Hernia,75,F,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]",0,0,0,0,0,0,0,0,0,0,0,0,0,1
6,00000003_003.png,Hernia|Infiltration,76,F,PA,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]",1,0,0,0,0,0,0,0,0,0,0,0,0,1
7,00000003_004.png,Hernia,77,F,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]",0,0,0,0,0,0,0,0,0,0,0,0,0,1
8,00000003_005.png,Hernia,78,F,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]",0,0,0,0,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112113,00030800_000.png,No Finding,33,F,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,0,0,0,0,0,0,0,0,0,0,0,0
112116,00030802_000.png,No Finding,28,M,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,0,0,0,0,0,0,0,0,0,0,0,0
112117,00030803_000.png,No Finding,42,F,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,0,0,0,0,0,0,0,0,0,0,0,0
112118,00030804_000.png,No Finding,29,F,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,0,0,0,0,0,0,0,0,0,0,0,0
112119,00030805_000.png,No Finding,26,M,PA,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [34]:
train_val_images = train_val_df["image_index"].tolist()
test_images = test_df["image_index"].tolist()

print(f"Number of training/validation images: {len(train_val_images)}")
print(f"Number of test images: {len(test_images)}")

intersection = set(train_val_images) & set(test_images)
print(f"Number of images in both sets: {len(intersection)}")

Number of training/validation images: 86524
Number of test images: 25596
Number of images in both sets: 0

### Saving data

In [37]:
out_dir = Path("data/02_intermediate/dataset_splits")
out_dir.mkdir(parents=True, exist_ok=True)

train_val_df.to_csv(out_dir / "train_val.csv", index=False)
test_df.to_csv(out_dir / "test.csv", index=False)